/**
 * The Astrolune ID domain model.
 *
 * Two rules hold across every shape in this file, and both exist so that the
 * mock transport in `mock.ts` can be replaced by a real one without a single
 * consumer changing:
 *
 * 1. **Amounts are strings of base units.** One Lune is 10⁹ base units and the
 *    representable ceiling is past `Number.MAX_SAFE_INTEGER`, so a balance is
 *    never a `number`. `format.ts` does the conversion with string arithmetic.
 * 2. **Timestamps are epoch milliseconds.** A number, not a `Date` and not an
 *    ISO string, because the countdown widgets subtract them every second and
 *    because a `Date` cannot survive `JSON.parse` of a persisted session.
 */

/* ------------------------------------------------------------------
   Identity
   ------------------------------------------------------------------ */

/** How the holder proved control of the account for the current session. */
export type AuthMethod = "wallet" | "passkey" | "email" | "recovery";

/**
 * Session lifecycle. `restoring` is the beat between the first client render
 * and the persisted session being read — distinct from `anonymous`, because a
 * widget that renders "Sign in" during a restore flickers on every reload.
 */
export type SessionStatus =
  | "restoring"
  | "anonymous"
  | "authenticating"
  | "authenticated";

/** Purchased capability level. Drives quotas rather than access. */
export type Tier = "free" | "plus" | "operator";

export type Identity = {
  /** `aid_` + 8 hex. Stable for the life of the account. */
  id: string;
  /** The account's canonical `.lune` name, or `null` before one is linked. */
  handle: string | null;
  displayName: string;
  /** Seed for the generated dot-matrix avatar — never an uploaded image. */
  avatarSeed: string;
  createdAt: number;
  tier: Tier;
  /**
   * 0–100, mirroring the node trust score the protocol computes. On an ID it
   * summarises linked-asset history, not consensus behaviour.
   */
  trust: number;
  /** True once any linked node has cleared the validator floor. */
  isValidator: boolean;
  /** Methods currently registered on the account, not just the one used now. */
  methods: AuthMethod[];
};

/* ------------------------------------------------------------------
   Linked assets
   ------------------------------------------------------------------ */

export type WalletKind = "hardware" | "software" | "contract" | "watch";

export type Wallet = {
  id: string;
  address: string;
  label: string;
  kind: WalletKind;
  /** Base units. */
  balance: string;
  /** Exactly one wallet is primary; it receives rewards and pays invoices. */
  primary: boolean;
  /** A watch-only wallet is linked without a signature and cannot spend. */
  verified: boolean;
  linkedAt: number;
};

export type DomainStatus = "active" | "grace" | "pending";

export type Domain = {
  name: string;
  status: DomainStatus;
  registeredAt: number;
  expiresAt: number;
  autoRenew: boolean;
  /** Address the ADDR record resolves to, or `null` when unset. */
  target: string | null;
  /** Number of records in the zone, of every type. */
  records: number;
};

/** A Share bucket — the storage layer, addressed by content. */
export type Bucket = {
  id: string;
  label: string;
  region: string;
  usedBytes: number;
  quotaBytes: number;
  /** Pinned objects. */
  pins: number;
  /** Replication factor across the storage set. */
  replicas: number;
  /** Gateway host for this bucket. */
  endpoint: string;
  status: "ready" | "syncing" | "degraded";
};

export type ProxyProtocol = "socks5" | "https" | "wireguard";
export type ProxyRotation = "static" | "per-request" | "hourly";

export type ProxyEndpoint = {
  id: string;
  label: string;
  region: string;
  protocol: ProxyProtocol;
  host: string;
  port: number;
  username: string;
  /** Regenerated by `rotateProxy`; never displayed until revealed. */
  secret: string;
  rotation: ProxyRotation;
  /** Included traffic and consumption for the current period, in gigabytes. */
  quotaGb: number;
  usedGb: number;
  expiresAt: number;
  status: "active" | "paused" | "expired";
};

/* ------------------------------------------------------------------
   Nodes
   ------------------------------------------------------------------ */

export type NodeRole = "relay" | "candidate" | "validator";

export type NodeStat = {
  id: string;
  /** `al-node-` + 8 hex, matching what SCAN indexes. */
  nodeId: string;
  label: string;
  role: NodeRole;
  region: string;
  version: string;
  status: "online" | "syncing" | "offline";
  uptimePct: number;
  peers: number;
  height: number;
  /** Missed votes as a share of votes owed, over the trailing window. */
  missRate: number;
  /** Last 24 samples of block-time, newest last. Drives the sparkline. */
  series: number[];
};

/** The extra panel a validator account gets. Absent for a relay-only holder. */
export type ValidatorInfo = {
  nodeId: string;
  /** Time-behaviour score, trust-graph weight, node-diversity and cost-of-dishonesty. */
  tbs: number;
  tgw: number;
  ndm: number;
  cod: number;
  /** Final consensus weight, and rank within the indexed set. */
  weight: number;
  rank: number;
  inCommittee: boolean;
  epochsInCommittee: number;
  missedVotes: number;
  /** Base units posted as the operational bond. Carries no consensus weight. */
  bond: string;
  /** Base units earned over the trailing 30 protocol days. */
  rewards30d: string;
  /**
   * `delta` is a pre-formatted display string such as `-0.4 TBS`, not an
   * amount: a penalty is scored against a weight component, so there is no one
   * unit for the UI to format it in.
   */
  penalties: { label: string; at: number; delta: string }[];
};

/* ------------------------------------------------------------------
   Catalogue and checkout
   ------------------------------------------------------------------ */

export type SkuKind = "domain" | "share" | "proxy" | "tier";

export type CatalogItem = {
  sku: string;
  kind: SkuKind;
  label: string;
  blurb: string;
  /** Base units. */
  price: string;
  period: "once" | "month" | "year";
  /** Rendered as a spec list on the card. Values are already formatted. */
  specs: { k: string; v: string }[];
};

export type InvoiceStatus =
  | "awaiting"
  | "confirming"
  | "paid"
  | "expired"
  | "failed";

export type Invoice = {
  id: string;
  sku: string;
  label: string;
  /** Base units. */
  amount: string;
  /** Deposit address. Single-use, derived per invoice. */
  address: string;
  /** Attached to the transfer so the payment binds to this invoice. */
  memo: string;
  network: "mainnet" | "testnet";
  createdAt: number;
  expiresAt: number;
  status: InvoiceStatus;
  confirmations: number;
  requiredConfirmations: number;
  txHash: string | null;
};

/* ------------------------------------------------------------------
   Store shape
   ------------------------------------------------------------------ */

export type IdState = {
  /**
   * False until the persisted session has been read on the client. Every
   * component that renders differently for a signed-in holder gates on this,
   * which is what keeps the server and the first client render identical.
   */
  ready: boolean;
  status: SessionStatus;
  /** The method currently being exercised, while `status` is authenticating. */
  pending: AuthMethod | null;
  error: string | null;
  identity: Identity | null;
  wallets: Wallet[];
  domains: Domain[];
  buckets: Bucket[];
  proxies: ProxyEndpoint[];
  nodes: NodeStat[];
  validator: ValidatorInfo | null;
  catalog: CatalogItem[];
  /** The open checkout, or `null` when nothing is being paid for. */
  invoice: Invoice | null;
};
